### ISSUE TITLE
Enhanced Spawn Selection

### ISSUE THREAD

**Issue by Johndow125** [Fallingsheep1985/0.14_DamYouSteam_Multi_NAPF#1]
am I right to say 
to add vip to ess

fixes\variables.sqf add 
 donorClassLvl1 = ["0","0","0"];
 donorClassLvl2 = ["0","0","0"];
 donorClassLvl3 = ["0","0","0"];
 donorClassLvl4 = ["0","0","0"];

or do you have it some ware else?

**Comment by Fallingsheep1985** [comment]
yes, but i would suggest you use 0.15 or 0.16 builds, as there is no support for 0.14 any more
